services:
  - type: web
    name: campus-lost-found-backend
    runtime: node
    rootDir: Backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: EMAIL_SERVICE
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_SECRET_CODE
        sync: false
      - key: OTP_EXPIRE_MINUTES
        value: "10"
